/**
 * Localization system for AIpedia
 */

// Default locale is English
let currentLocale = 'en';

// Locale data for different languages
const locales = {
    // English
    'en': {
        // Search
        'search_placeholder': 'Search for any topic...',
        'search_button': 'Search',
        'estimated_time': 'Estimated wait time: {0} seconds',
        'history_toggle': 'Search History',
        'no_history': 'No search history yet',
        'delete_from_history': 'Delete from history',
        
        // Writing styles
        'writing_style': 'Writing Style',
        'style_normal': 'Normal',
        'style_formal': 'Formal',
        'style_accessible': 'Accessible',
        'style_explanatory': 'Explanatory',
        'style_concise': 'Concise',
        
        // Age-targeted writing styles
        'age_0_10': 'Age 0-10',
        'age_11_16': 'Age 11-16',
        'age_17_25': 'Age 17-25',
        'age_25_plus': 'Age 25+',
        
        // Audio player
        'listen_to_summary': 'Listen to the summary',
        'tts_not_available': 'Text-to-speech is not available for this article.',
        
        // Article
        'contents': 'Contents',
        'references': 'References',
        'geek_metrics': 'Generation Metrics',
        'generation_time': 'Generation time: {0}s',
        'tokens_used': 'Tokens used: ~{0}',
        'estimated_cost': 'Estimated cost: ${0}',
        
        // AI warning
        'ai_warning_title': 'AI-Generated Content',
        'ai_warning_message': 'This content was generated by AI and may contain inaccuracies. Always verify important information from reliable sources.',
        'i_understand': 'I understand',
        'remind_me_later': 'Remind me later',
        
        // Customization modal
        'customize_title': 'Customize Genipedia',
        'theme_title': 'Theme',
        'theme_light': 'Light',
        'theme_dark': 'Dark',
        'accent_color_title': 'Accent Color',
        'font_title': 'Font',
        'font_size_title': 'Font Size',
        'beta_features_title': 'Beta Features',
        'licenses_button': 'Licenses',
        'image_suggestion_title': 'AI Image Suggestion',
        'image_suggestion_description': 'Uses AI to suggest better image search terms for more relevant article images',
        'age_targeted_title': 'Age-Targeted Writing',
        'age_targeted_description': 'Adapts content to specific age groups with appropriate vocabulary and complexity',
        'tts_title': 'Text-to-Speech',
        'tts_description': 'Converts article summaries to natural-sounding speech',
        'tts_api_label': 'TTS API:',
        'tts_free_api': 'Free API',
        'tts_elevenlabs': 'ElevenLabs (Custom API Key)',
        'enter_api_key': 'Enter your ElevenLabs API key',
        'save_button': 'Save',
        
        // Article caching
        'article_caching_title': 'Article Caching',
        'article_caching_description': 'Saves articles and images locally to reduce loading times and API usage',
        
        // Donation banner
        'support_title': 'Support Genipedia',
        'support_message': 'If Genipedia is free, it\'s thanks to donations. Please consider donating to keep the project alive and cover the API costs.',
        'support_button': 'Support on Ko-Fi',
        'maybe_later': 'Maybe later',
        
        // Customization
        'customization': 'Customization',
        'theme': 'Theme',
        'light_theme': 'Light',
        'dark_theme': 'Dark',
        'accent_color': 'Accent Color',
        'font_family': 'Font Family',
        'font_size': 'Font Size',
        'small': 'Small',
        'medium': 'Medium',
        'large': 'Large',
        'close': 'Close',
        
        // API Settings
        'api_settings': 'API Settings',
        'elevenlabs_api_key': 'ElevenLabs API Key',
        'api_key_info': 'Required for text-to-speech functionality. Get your API key from',
        'save_api_key': 'Save',
        'api_key_saved': 'API key saved successfully',
        'api_key_set': 'API key is set',
        'api_key_invalid': 'Please enter a valid API key',
        
        // Error messages
        'error_title': 'Error Generating Article',
        'error_message': 'Sorry, we couldn\'t generate an article for your query. Please try again later.',
        
        // Beta Features
        'ai_image_suggestion': 'AI Image Suggestion',
        'ai_image_suggestion_desc': 'Uses AI to suggest better image search terms for more relevant article images',
        'text_to_speech': 'Text-to-Speech',
        'text_to_speech_desc': 'Converts article summaries to natural-sounding speech using ElevenLabs',
        'beta_info': 'Beta features may not work perfectly and could affect performance.',
        'licenses': 'Licenses',
        'report_bug': 'Report a Bug',
        'contact_us': 'If you\'ve encountered a bug or have any issues with Genipedia, please contact us at:',
        
        // Top banner
        'top_banner_message': '🎉 First version of Genipedia is available 🎉  Consider donating!',
        'donate_button': 'Donate',
        
        // Beta Feature Tooltips
        'image_suggestion_tooltip': 'This feature uses AI to suggest better image search terms for more relevant images. Beta features may not work perfectly and could affect performance.',
        'age_targeted_tooltip': 'This feature adapts the writing style to specific age groups. When enabled, it replaces the standard writing styles with age-targeted options.',
        'tts_tooltip': 'This feature uses text-to-speech to convert article summaries to speech. By default, a free API is used, but you can also use ElevenLabs for higher quality.',
        'article_caching_tooltip': 'This feature saves articles and images locally to reduce loading times and API usage. Disable if you prefer not to store content on your device.',
    },
    
    // French
    'fr': {
        // Search
        'search_placeholder': 'Rechercher un sujet...',
        'search_button': 'Rechercher',
        'estimated_time': 'Temps d\'attente estimé: {0} secondes',
        'history_toggle': 'Historique de recherche',
        'no_history': 'Pas encore d\'historique de recherche',
        'delete_from_history': 'Supprimer de l\'historique',
        
        // Writing styles
        'writing_style': 'Style d\'écriture',
        'style_normal': 'Normal',
        'style_formal': 'Formel',
        'style_accessible': 'Accessible',
        'style_explanatory': 'Explicatif',
        'style_concise': 'Concis',
        
        // Age-targeted writing styles
        'age_0_10': 'Âge 0-10',
        'age_11_16': 'Âge 11-16',
        'age_17_25': 'Âge 17-25',
        'age_25_plus': 'Âge 25+',
        
        // Audio player
        'listen_to_summary': 'Écouter le résumé',
        'tts_not_available': 'La synthèse vocale n\'est pas disponible pour cet article.',
        
        // Article
        'contents': 'Sommaire',
        'references': 'Références',
        'geek_metrics': 'Métriques de Génération',
        'generation_time': 'Temps de génération: {0}s',
        'tokens_used': 'Tokens utilisés: ~{0}',
        'estimated_cost': 'Coût estimé: ${0}',
        
        // AI warning
        'ai_warning_title': 'Contenu généré par IA',
        'ai_warning_message': 'Ce contenu a été généré par une IA et peut contenir des inexactitudes. Vérifiez toujours les informations importantes auprès de sources fiables.',
        'i_understand': 'Je comprends',
        'remind_me_later': 'Me le rappeler plus tard',
        
        // Customization modal
        'customize_title': 'Personnaliser Genipedia',
        'theme_title': 'Thème',
        'theme_light': 'Clair',
        'theme_dark': 'Sombre',
        'accent_color_title': 'Couleur d\'accent',
        'font_title': 'Police',
        'font_size_title': 'Taille de police',
        'beta_features_title': 'Fonctionnalités Bêta',
        'licenses_button': 'Licences',
        'image_suggestion_title': 'Suggestion d\'Images par IA',
        'image_suggestion_description': 'Utilise l\'IA pour suggérer de meilleurs termes de recherche d\'images pour des articles plus pertinents',
        'age_targeted_title': 'Écriture Âge-Ciblée',
        'age_targeted_description': 'Adapte le contenu aux groupes d\'âge avec le vocabulaire et la complexité appropriés',
        'tts_title': 'Synthèse Vocale',
        'tts_description': 'Convertit les résumés d\'articles en voix naturelle',
        'tts_api_label': 'API TTS:',
        'tts_free_api': 'API Gratuit',
        'tts_elevenlabs': 'ElevenLabs (Clé API Personnalisée)',
        'enter_api_key': 'Entrez votre clé API ElevenLabs',
        'save_button': 'Enregistrer',
        
        // Article caching
        'article_caching_title': 'Mise en cache des Articles',
        'article_caching_description': 'Enregistre les articles et les images localement pour réduire les temps de chargement et l\'utilisation de l\'API',
        
        // Donation banner
        'support_title': 'Soutenez Genipedia',
        'support_message': 'Si Genipedia est gratuit, c\'est grâce aux dons. Merci de considérer un don pour maintenir le projet en vie et couvrir les coûts des API.',
        'support_button': 'Soutenir sur Ko-Fi',
        'maybe_later': 'Peut-être plus tard',
        
        // Customization
        'customization': 'Personnalisation',
        'theme': 'Thème',
        'light_theme': 'Clair',
        'dark_theme': 'Sombre',
        'accent_color': 'Couleur d\'accent',
        'font_family': 'Police',
        'font_size': 'Taille de police',
        'small': 'Petite',
        'medium': 'Moyenne',
        'large': 'Grande',
        'close': 'Fermer',
        
        // API Settings
        'api_settings': 'Paramètres API',
        'elevenlabs_api_key': 'Clé API ElevenLabs',
        'api_key_info': 'Nécessaire pour la fonctionnalité de synthèse vocale. Obtenez votre clé API sur',
        'save_api_key': 'Enregistrer',
        'api_key_saved': 'Clé API enregistrée avec succès',
        'api_key_set': 'La clé API est définie',
        'api_key_invalid': 'Veuillez entrer une clé API valide',
        
        // Error messages
        'error_title': 'Erreur de génération d\'article',
        'error_message': 'Désolé, nous n\'avons pas pu générer un article pour votre requête. Veuillez réessayer plus tard.',
        
        // Beta Features
        'ai_image_suggestion': 'Suggestion d\'Images par IA',
        'ai_image_suggestion_desc': 'Utilise l\'IA pour suggérer de meilleurs termes de recherche d\'images pour des articles plus pertinents',
        'text_to_speech': 'Synthèse Vocale',
        'text_to_speech_desc': 'Convertit les résumés d\'articles en voix naturelle avec ElevenLabs',
        'beta_info': 'Les fonctionnalités bêta peuvent ne pas fonctionner parfaitement et pourraient affecter les performances.',
        'licenses': 'Licences',
        'report_bug': 'Signaler un Bug',
        'contact_us': 'Si vous avez rencontré un bug ou avez des problèmes avec Genipedia, veuillez nous contacter à :',
        
        // Top banner
        'top_banner_message': '🎉 La première version de Genipedia est disponible 🎉  Pensez à faire un don ! ',
        'donate_button': 'Faire un don',
        
        // Beta Feature Tooltips
        'image_suggestion_tooltip': 'Cette fonctionnalité utilise l\'IA pour suggérer de meilleurs termes de recherche d\'images pour des résultats plus pertinents. Les fonctionnalités bêta peuvent ne pas fonctionner parfaitement et pourraient affecter les performances.',
        'age_targeted_tooltip': 'Cette fonctionnalité adapte le style d\'écriture à des groupes d\'âge spécifiques. Lorsqu\'elle est activée, elle remplace les styles d\'écriture standard par des options ciblées par âge.',
        'tts_tooltip': 'Cette fonctionnalité utilise la synthèse vocale pour convertir les résumés d\'articles en discours. Par défaut, une API gratuite est utilisée, mais vous pouvez également utiliser ElevenLabs pour une meilleure qualité.',
        'article_caching_tooltip': 'Cette fonctionnalité enregistre les articles et les images localement pour réduire les temps de chargement et l\'utilisation de l\'API. Désactivez-la si vous préférez ne pas stocker de contenu sur votre appareil.',
    },
    
    // Spanish
    'es': {
        // Search
        'search_placeholder': 'Buscar cualquier tema...',
        'search_button': 'Buscar',
        'estimated_time': 'Tiempo de espera estimado: {0} segundos',
        'history_toggle': 'Historial de búsqueda',
        'no_history': 'Aún no hay historial de búsqueda',
        'delete_from_history': 'Eliminar del historial',
        
        // Writing styles
        'writing_style': 'Estilo de escritura',
        'style_normal': 'Normal',
        'style_formal': 'Formal',
        'style_accessible': 'Accesible',
        'style_explanatory': 'Explicativo',
        'style_concise': 'Conciso',
        
        // Age-targeted writing styles
        'age_0_10': 'Edad 0-10',
        'age_11_16': 'Edad 11-16',
        'age_17_25': 'Edad 17-25',
        'age_25_plus': 'Edad 25+',
        
        // Audio player
        'listen_to_summary': 'Escuchar el resumen',
        'tts_not_available': 'La síntesis de voz no está disponible para este artículo.',
        
        // Article
        'contents': 'Contenido',
        'references': 'Referencias',
        'geek_metrics': 'Métricas de Generación',
        'generation_time': 'Tiempo de generación: {0}s',
        'tokens_used': 'Tokens utilizados: ~{0}',
        'estimated_cost': 'Costo estimado: ${0}',
        
        // AI warning
        'ai_warning_title': 'Contenido generado por IA',
        'ai_warning_message': 'Este contenido fue generado por IA y puede contener inexactitudes. Verifique siempre la información importante en fuentes confiables.',
        'i_understand': 'Entiendo',
        'remind_me_later': 'Recordármelo más tarde',
        
        // Customization modal
        'customize_title': 'Personalizar Genipedia',
        'theme_title': 'Tema',
        'theme_light': 'Claro',
        'theme_dark': 'Oscuro',
        'accent_color_title': 'Color de acento',
        'font_title': 'Tipo de letra',
        'font_size_title': 'Tamaño de letra',
        'beta_features_title': 'Funciones Beta',
        'licenses_button': 'Licencias',
        'image_suggestion_title': 'Sugerencia de Imágenes por IA',
        'image_suggestion_description': 'Utiliza IA para sugerir mejores términos de búsqueda de imágenes para artículos más relevantes',
        'age_targeted_title': 'Escritura Âge-Ciblada',
        'age_targeted_description': 'Adapta el contenido a grupos de edad con vocabulario y complejidad apropiados',
        'tts_title': 'Texto a Voz',
        'tts_description': 'Convierte resúmenes de artículos en voz natural',
        'tts_api_label': 'API TTS:',
        'tts_free_api': 'API Gratuita',
        'tts_elevenlabs': 'ElevenLabs (Clave API Personalizada)',
        'enter_api_key': 'Ingrese su clave API ElevenLabs',
        'save_button': 'Guardar',
        
        // Article caching
        'article_caching_title': 'Almacenamiento de Artículos',
        'article_caching_description': 'Guarda artículos y imágenes localmente para reducir los tiempos de carga y el uso de la API',
        
        // Donation banner
        'support_title': 'Apoya a Genipedia',
        'support_message': 'Si Genipedia es gratuito, es gracias a las donaciones. Por favor, considera donar para mantener vivo el proyecto y cubrir los costos de API.',
        'support_button': 'Apoyar en Ko-Fi',
        'maybe_later': 'Quizás más tarde',
        
        // Customization
        'customization': 'Personalización',
        'theme': 'Tema',
        'light_theme': 'Claro',
        'dark_theme': 'Oscuro',
        'accent_color': 'Color de acento',
        'font_family': 'Tipo de letra',
        'font_size': 'Tamaño de letra',
        'small': 'Pequeño',
        'medium': 'Mediano',
        'large': 'Grande',
        'close': 'Cerrar',
        
        // API Settings
        'api_settings': 'Configuración API',
        'elevenlabs_api_key': 'Clave API ElevenLabs',
        'api_key_info': 'Necesario para la funcionalidad de síntesis de voz. Obtener su clave API en',
        'save_api_key': 'Guardar',
        'api_key_saved': 'Clave API guardada correctamente',
        'api_key_set': 'La clave API está configurada',
        'api_key_invalid': 'Ingrese una clave API válida',
        
        // Error messages
        'error_title': 'Error al generar el artículo',
        'error_message': 'Lo sentimos, no pudimos generar un artículo para su consulta. Por favor, inténtelo de nuevo más tarde.',
        
        // Beta Features
        'ai_image_suggestion': 'Sugerencia de Imágenes por IA',
        'ai_image_suggestion_desc': 'Utiliza IA para sugerir mejores términos de búsqueda de imágenes para artículos más relevantes',
        'text_to_speech': 'Texto a Voz',
        'text_to_speech_desc': 'Convierte resúmenes de artículos en voz natural usando ElevenLabs',
        'beta_info': 'Las funciones beta pueden no funcionar perfectamente y podrían afectar el rendimiento.',
        'licenses': 'Licencias',
        'report_bug': 'Reportar un Error',
        'contact_us': 'Si has encontrado un error o tienes problemas con Genipedia, contáctanos en:',
        
        // Top banner
        'top_banner_message': '🎉 La primera versión de Genipedia está disponible 🎉  Considera donar!',
        'donate_button': 'Donar',
        
        // Beta Feature Tooltips
        'image_suggestion_tooltip': 'Esta función utiliza IA para sugerir mejores términos de búsqueda de imágenes para resultados más relevantes. Las funciones beta pueden no funcionar perfectamente y podrían afectar el rendimiento.',
        'age_targeted_tooltip': 'Esta función adapta el estilo de escritura a grupos de edad específicos. Cuando está habilitada, reemplaza los estilos de escritura estándar con opciones dirigidas por edad.',
        'tts_tooltip': 'Esta función utiliza texto a voz para convertir los resúmenes de artículos en discurso. Por defecto, se utiliza una API gratuita, pero también puede usar ElevenLabs para una mayor calidad.',
        'article_caching_tooltip': 'Esta función guarda artículos e imágenes localmente para reducir los tiempos de carga y el uso de API. Desactívela si prefiere no almacenar contenido en su dispositivo.',
    },
    
    // German
    'de': {
        // Search
        'search_placeholder': 'Suche nach einem Thema...',
        'search_button': 'Suchen',
        'estimated_time': 'Geschätzte Wartezeit: {0} Sekunden',
        'history_toggle': 'Suchverlauf',
        'no_history': 'Noch kein Suchverlauf',
        'delete_from_history': 'Aus Verlauf löschen',
        
        // Writing styles
        'writing_style': 'Schreibstil',
        'style_normal': 'Normal',
        'style_formal': 'Formell',
        'style_accessible': 'Zugänglich',
        'style_explanatory': 'Erklärend',
        'style_concise': 'Prägnant',
        
        // Age-targeted writing styles
        'age_0_10': 'Alter 0-10',
        'age_11_16': 'Alter 11-16',
        'age_17_25': 'Alter 17-25',
        'age_25_plus': 'Alter 25+',
        
        // Audio player
        'listen_to_summary': 'Zusammenfassung anhören',
        'tts_not_available': 'Text-to-Speech ist für diesen Artikel nicht verfügbar.',
        
        // Article
        'contents': 'Inhalt',
        'references': 'Referenzen',
        'geek_metrics': 'Generierungsmetriken',
        'generation_time': 'Generierungszeit: {0}s',
        'tokens_used': 'Verwendete Tokens: ~{0}',
        'estimated_cost': 'Geschätzte Kosten: ${0}',
        
        // AI warning
        'ai_warning_title': 'KI-generierter Inhalt',
        'ai_warning_message': 'Dieser Inhalt wurde von einer KI generiert und kann Ungenauigkeiten enthalten. Überprüfen Sie wichtige Informationen immer anhand zuverlässiger Quellen.',
        'i_understand': 'Ich verstehe',
        'remind_me_later': 'Später erinnern',
        
        // Customization modal
        'customize_title': 'Genipedia anpassen',
        'theme_title': 'Thema',
        'theme_light': 'Hell',
        'theme_dark': 'Dunkel',
        'accent_color_title': 'Akzentfarbe',
        'font_title': 'Schriftart',
        'font_size_title': 'Schriftgröße',
        'beta_features_title': 'Beta-Funktionen',
        'licenses_button': 'Lizenzen',
        'image_suggestion_title': 'KI-Bildvorschläge',
        'image_suggestion_description': 'Verwendet KI, um bessere Bildsuchbegriffe für relevantere Artikelbilder vorzuschlagen',
        'age_targeted_title': 'Âge-zielende Schrift',
        'age_targeted_description': 'Passt den Inhalt an bestimmte Altersgruppen mit dem passenden Vokabular und der Komplexität an',
        'tts_title': 'Text-zu-Sprache',
        'tts_description': 'Konvertiert Artikelzusammenfassungen in natürlich klingende Sprache',
        'tts_api_label': 'TTS API:',
        'tts_free_api': 'Freie API',
        'tts_elevenlabs': 'ElevenLabs (Custom API Key)',
        'enter_api_key': 'ElevenLabs API-Schlüssel eingeben',
        'save_button': 'Speichern',
        
        // Article caching
        'article_caching_title': 'Artikel-Caching',
        'article_caching_description': 'Artikel und Bilder lokal speichern, um Ladezeiten und API-Nutzung zu reduzieren',
        
        // Donation banner
        'support_title': 'Unterstütze Genipedia',
        'support_message': 'Wenn Genipedia kostenlos ist, dann dank Spenden. Bitte erwäge eine Spende, um das Projekt am Leben zu erhalten und die API-Kosten zu decken.',
        'support_button': 'Auf Ko-Fi unterstützen',
        'maybe_later': 'Vielleicht später',
        
        // Customization
        'customization': 'Anpassung',
        'theme': 'Thema',
        'light_theme': 'Hell',
        'dark_theme': 'Dunkel',
        'accent_color': 'Akzentfarbe',
        'font_family': 'Schriftart',
        'font_size': 'Schriftgröße',
        'small': 'Klein',
        'medium': 'Mittel',
        'large': 'Groß',
        'close': 'Schließen',
        
        // API Settings
        'api_settings': 'API-Einstellungen',
        'elevenlabs_api_key': 'ElevenLabs API-Schlüssel',
        'api_key_info': 'Erforderlich für die Sprachsynthese. API-Schlüssel erhalten Sie von',
        'save_api_key': 'Speichern',
        'api_key_saved': 'API-Schlüssel erfolgreich gespeichert',
        'api_key_set': 'API-Schlüssel ist eingestellt',
        'api_key_invalid': 'Geben Sie eine gültige API-Schlüssel ein',
        
        // Error messages
        'error_title': 'Fehler beim Generieren des Artikels',
        'error_message': 'Entschuldigung, wir konnten keinen Artikel für Ihre Anfrage generieren. Bitte versuchen Sie es später erneut.',
        
        // Beta Features
        'ai_image_suggestion': 'KI-Bildvorschläge',
        'ai_image_suggestion_desc': 'Verwendet KI, um bessere Bildsuchbegriffe für relevantere Artikelbilder vorzuschlagen',
        'text_to_speech': 'Text-zu-Sprache',
        'text_to_speech_desc': 'Konvertiert Artikelzusammenfassungen in natürlich klingende Sprache mit ElevenLabs',
        'beta_info': 'Beta-Funktionen funktionieren möglicherweise nicht perfekt und könnten die Leistung beeinträchtigen.',
        'licenses': 'Lizenzen',
        'report_bug': 'Fehler Melden',
        'contact_us': 'Wenn Sie einen Fehler gefunden haben oder Probleme mit Genipedia haben, kontaktieren Sie uns bitte unter:',
        
        // Top banner
        'top_banner_message': '🎉 Die erste Version von Genipedia ist verfügbar 🎉  Spenden Sie bitte!',
        'donate_button': 'Spenden',
        
        // Beta Feature Tooltips
        'image_suggestion_tooltip': 'Diese Funktion verwendet KI, um bessere Bildsuchbegriffe für relevantere Ergebnisse vorzuschlagen. Beta-Funktionen funktionieren möglicherweise nicht perfekt und könnten die Leistung beeinträchtigen.',
        'age_targeted_tooltip': 'Diese Funktion passt den Schreibstil an bestimmte Altersgruppen an. Wenn aktiviert, ersetzt sie die Standard-Schreibstile durch altersspezifische Optionen.',
        'tts_tooltip': 'Diese Funktion verwendet Text-zu-Sprache, um Artikelzusammenfassungen in Sprache umzuwandeln. Standardmäßig wird eine kostenlose API verwendet, aber Sie können auch ElevenLabs für höhere Qualität verwenden.',
        'article_caching_tooltip': 'Diese Funktion speichert Artikel und Bilder lokal, um Ladezeiten und API-Nutzung zu reduzieren. Deaktivieren Sie sie, wenn Sie es vorziehen, keine Inhalte auf Ihrem Gerät zu speichern.',
    },
    
    // Japanese
    'ja': {
        // Search
        'search_placeholder': 'トピックを検索...',
        'search_button': '検索',
        'estimated_time': '推定待ち時間: {0}秒',
        'history_toggle': '検索履歴',
        'no_history': '検索履歴はありません',
        'delete_from_history': '履歴から削除',
        
        // Writing styles
        'writing_style': '文体',
        'style_normal': '標準',
        'style_formal': '形式的',
        'style_accessible': '分かりやすい',
        'style_explanatory': '説明的',
        'style_concise': '簡潔',
        
        // Age-targeted writing styles
        'age_0_10': '年齢 0-10',
        'age_11_16': '年齢 11-16',
        'age_17_25': '年齢 17-25',
        'age_25_plus': '年齢 25+',
        
        // Audio player
        'listen_to_summary': '要約を聞く',
        'tts_not_available': 'この記事では音声読み上げは利用できません。',
        
        // Article
        'contents': '目次',
        'references': '参考文献',
        'geek_metrics': '生成メトリクス',
        'generation_time': '生成時間: {0}秒',
        'tokens_used': '使用トークン数: ~{0}',
        'estimated_cost': '推定コスト: ${0}',
        
        // AI warning
        'ai_warning_title': 'AI生成コンテンツ',
        'ai_warning_message': 'このコンテンツはAIによって生成されており、不正確な情報が含まれている可能性があります。重要な情報は信頼できる情報源で必ず確認してください。',
        'i_understand': '理解しました',
        'remind_me_later': '後で通知',
        
        // Customization modal
        'customize_title': 'Genipediaをカスタマイズ',
        'theme_title': 'テーマ',
        'theme_light': 'ライト',
        'theme_dark': 'ダーク',
        'accent_color_title': 'アクセントカラー',
        'font_title': 'フォント',
        'font_size_title': 'フォントサイズ',
        'beta_features_title': 'ベータ機能',
        'licenses_button': 'ライセンス',
        'image_suggestion_title': 'AI画像提案',
        'image_suggestion_description': 'AIを使用してより関連性の高い記事画像のための検索用語を提案',
        'age_targeted_title': '年齢別文章',
        'age_targeted_description': '適切な言葉遣いと複雑さで内容を年齢層に合わせる',
        'tts_title': '音声読み上げ',
        'tts_description': '記事の要約を自然な声に変換',
        'tts_api_label': 'TTS API:',
        'tts_free_api': '無料API',
        'tts_elevenlabs': 'ElevenLabs (カスタムAPIキー)',
        'enter_api_key': 'ElevenLabs APIキーを入力',
        'save_button': '保存',
        
        // Article caching
        'article_caching_title': '記事キャッシュ',
        'article_caching_description': '記事と画像をローカルに保存してロード時間とAPI使用を削減',
        
        // Donation banner
        'support_title': 'Genipediaをサポート',
        'support_message': 'Genipediaが無料で利用できるのは、寄付のおかげです。プロジェクトの継続とAPIコストをカバーするために、ご寄付をご検討ください。',
        'support_button': 'Ko-Fiでサポート',
        'maybe_later': '後で',
        
        // Customization
        'customization': 'カスタマイズ',
        'theme': 'テーマ',
        'light_theme': 'ライト',
        'dark_theme': 'ダーク',
        'accent_color': 'アクセントカラー',
        'font_family': 'フォント',
        'font_size': 'フォントサイズ',
        'small': '小',
        'medium': '中',
        'large': '大',
        'close': '閉じる',
        
        // API Settings
        'api_settings': 'API設定',
        'elevenlabs_api_key': 'ElevenLabs APIキー',
        'api_key_info': '音声読み上げ機能に必要です。APIキーの取得先:',
        'save_api_key': '保存',
        'api_key_saved': 'APIキーが正常に保存されました',
        'api_key_set': 'APIキーが設定されています',
        'api_key_invalid': '有効なAPIキーを入力してください',
        
        // Error messages
        'error_title': '記事生成エラー',
        'error_message': '申し訳ありません。クエリに対する記事を生成できませんでした。後でもう一度お試しください。',
        
        // Beta Features
        'ai_image_suggestion': 'AI画像提案',
        'ai_image_suggestion_desc': 'AIを使用してより関連性の高い記事画像のための検索用語を提案',
        'text_to_speech': '音声読み上げ',
        'text_to_speech_desc': 'ElevenLabsを使用して記事の要約を自然な音声に変換',
        'beta_info': 'ベータ機能は完全には動作せず、パフォーマンスに影響を与える可能性があります。',
        'licenses': 'ライセンス',
        'report_bug': 'バグを報告',
        'contact_us': 'バグが発生した場合や、Genipediaに関する問題がございましたら、以下のアドレスまでご連絡ください：',
        
        // Top banner
        'top_banner_message': '🎉 Genipediaの最初のバージョンが利用可能になりました 🎉 寄付をご検討ください',
        'donate_button': '寄付する',
        
        // Beta Feature Tooltips
        'image_suggestion_tooltip': 'この機能はAIを使用して、より関連性の高い結果を得るために、より適切な画像検索用語を提案します。ベータ機能は完全に機能しない場合があり、パフォーマンスに影響を与える可能性があります。',
        'age_targeted_tooltip': 'この機能は特定の年齢層に合わせて文章スタイルを調整します。有効にすると、標準の文章スタイルが年齢別のオプションに置き換わります。',
        'tts_tooltip': 'この機能はテキスト読み上げを使用して、記事の要約を音声に変換します。デフォルトでは無料のAPIが使用されますが、より高品質のためにElevenLabsを使用することもできます。',
        'article_caching_tooltip': 'この機能は記事と画像をローカルに保存し、読み込み時間とAPI使用量を削減します。デバイスにコンテンツを保存したくない場合は無効にしてください。',
    }
};

// Initialize the global AIPediaLocales object
window.AIPediaLocales = {
    locales: locales,
    
    /**
     * Gets a localized string by key
     * @param {string} key - The key to look up
     * @param {...any} args - Arguments to replace placeholders in the string
 * @returns {string} - The localized string
 */
    getLocaleString: function(key, ...args) {
    // Get the current locale data
    const localeData = locales[currentLocale] || locales['en'];
    
    // Get the string from the locale data
        let str = localeData[key] || key;
    
    // Replace placeholders with arguments
    if (args.length > 0) {
            args.forEach((arg, index) => {
                str = str.replace(`{${index}}`, arg);
        });
    }
    
    return str;
    },

/**
 * Sets the current locale
 * @param {string} locale - The locale code to set
 */
    setLocale: function(locale) {
    if (locales[locale]) {
        currentLocale = locale;
            // Save the locale to localStorage
            localStorage.setItem('aipedia_locale', locale);
            console.log('Locale set to:', locale);
            
            // Update UI with new locale
            this.updateUIWithLocale();
    } else {
            console.warn('Locale not found:', locale);
        }
    },
    
    /**
     * Gets the current locale
     * @returns {string} - The current locale code
     */
    getLocale: function() {
        return currentLocale;
    },

/**
 * Loads the saved locale from localStorage
 */
    loadSavedLocale: function() {
        try {
            // Try to get the browser language first if no saved locale
            const savedLocale = localStorage.getItem('aipedia_locale') || navigator.language.split('-')[0];
            
            if (savedLocale) {
                this.setLocale(savedLocale);
                
                // Update the language selector to match the saved locale
                const languageSelect = document.getElementById('language-select');
                if (languageSelect) {
                    // Check if the saved locale is available in the options
                    const options = Array.from(languageSelect.options);
                    const localeOption = options.find(option => option.value === savedLocale);
                    
                    if (localeOption) {
                        languageSelect.value = savedLocale;
                    }
                }
            }
        } catch (error) {
            console.error('Error loading saved locale:', error);
        }
    },
    
    /**
     * Updates the UI with the current locale
     */
    updateUIWithLocale: function() {
        try {
            // Update search placeholder
            const searchBar = document.getElementById('search-bar');
            if (searchBar) {
                searchBar.placeholder = this.getLocaleString('search_placeholder');
            }
            
            // Update search button
            const searchButton = document.getElementById('search-button');
            if (searchButton) {
                searchButton.textContent = this.getLocaleString('search_button');
            }
            
            // Update history toggle
            const historyToggle = document.querySelector('.history-toggle-text');
            if (historyToggle) {
                historyToggle.textContent = this.getLocaleString('history_toggle');
            }

            // Update writing style select label and options
            const writingStyleSelect = document.getElementById('writing-style-select');
            if (writingStyleSelect) {
                // Only update standard writing styles, not age-targeted ones
                const standardStyles = ['normal', 'formal', 'accessible', 'explanatory', 'concise'];
                const options = writingStyleSelect.options;
                
                for (let i = 0; i < options.length; i++) {
                    const option = options[i];
                    // Only update if it's a standard style
                    if (standardStyles.includes(option.value)) {
                        const styleKey = `style_${option.value}`;
                        option.textContent = this.getLocaleString(styleKey);
                    }
                }
            }
            
            // Update customization modal
            const customizeTitle = document.getElementById('customize-title');
            if (customizeTitle) {
                customizeTitle.textContent = this.getLocaleString('customize_title');
            }
            
            const themeTitle = document.getElementById('theme-title');
            if (themeTitle) {
                themeTitle.textContent = this.getLocaleString('theme_title');
            }
            
            const themeLightText = document.getElementById('theme-light-text');
            if (themeLightText) {
                themeLightText.textContent = this.getLocaleString('theme_light');
            }
            
            const themeDarkText = document.getElementById('theme-dark-text');
            if (themeDarkText) {
                themeDarkText.textContent = this.getLocaleString('theme_dark');
            }
            
            const accentColorTitle = document.getElementById('accent-color-title');
            if (accentColorTitle) {
                accentColorTitle.textContent = this.getLocaleString('accent_color_title');
            }
            
            const fontTitle = document.getElementById('font-title');
            if (fontTitle) {
                fontTitle.textContent = this.getLocaleString('font_title');
            }
            
            const fontSizeTitle = document.getElementById('font-size-title');
            if (fontSizeTitle) {
                fontSizeTitle.textContent = this.getLocaleString('font_size_title');
            }
            
            // Update beta features titles and descriptions
            const betaFeaturesTitle = document.getElementById('beta-features-title');
            if (betaFeaturesTitle) {
                betaFeaturesTitle.textContent = this.getLocaleString('beta_features_title');
            }
            
            // Image suggestion beta feature
            const imageSuggestionLabel = document.getElementById('image-suggestion-label');
            if (imageSuggestionLabel) {
                imageSuggestionLabel.textContent = this.getLocaleString('image_suggestion_title');
            }
            
            const imageSuggestionDesc = imageSuggestionLabel?.closest('.beta-feature')?.querySelector('.beta-feature-description');
            if (imageSuggestionDesc) {
                imageSuggestionDesc.textContent = this.getLocaleString('image_suggestion_description');
            }
            
            // Add tooltip translation for image suggestion
            const imageSuggestionTooltip = imageSuggestionLabel?.closest('.beta-feature')?.querySelector('.beta-tooltip');
            if (imageSuggestionTooltip) {
                imageSuggestionTooltip.textContent = this.getLocaleString('image_suggestion_tooltip');
            }
            
            // Age-targeted beta feature
            const ageTargetedLabel = document.getElementById('age-targeted-label');
            if (ageTargetedLabel) {
                ageTargetedLabel.textContent = this.getLocaleString('age_targeted_title');
            }
            
            const ageTargetedDesc = ageTargetedLabel?.closest('.beta-feature')?.querySelector('.beta-feature-description');
            if (ageTargetedDesc) {
                ageTargetedDesc.textContent = this.getLocaleString('age_targeted_description');
            }
            
            // Add tooltip translation for age-targeted
            const ageTargetedTooltip = ageTargetedLabel?.closest('.beta-feature')?.querySelector('.beta-tooltip');
            if (ageTargetedTooltip) {
                ageTargetedTooltip.textContent = this.getLocaleString('age_targeted_tooltip');
            }
            
            // Text-to-speech beta feature
            const elevenlabsLabel = document.getElementById('elevenlabs-label');
            if (elevenlabsLabel) {
                // Keep the beta tag and add the translation
                const betaTag = elevenlabsLabel.querySelector('.beta-tag');
                if (betaTag) {
                    elevenlabsLabel.textContent = '';
                    elevenlabsLabel.appendChild(betaTag);
                    elevenlabsLabel.appendChild(document.createTextNode(' ' + this.getLocaleString('tts_title')));
                } else {
                    elevenlabsLabel.textContent = this.getLocaleString('tts_title');
                }
            }
            
            const ttsDesc = elevenlabsLabel?.closest('.beta-feature')?.querySelector('.beta-feature-description');
            if (ttsDesc) {
                ttsDesc.textContent = this.getLocaleString('tts_description');
            }
            
            // Add tooltip translation for text-to-speech
            const ttsTooltip = elevenlabsLabel?.closest('.beta-feature')?.querySelector('.beta-tooltip');
            if (ttsTooltip) {
                ttsTooltip.textContent = this.getLocaleString('tts_tooltip');
            }
            
            // Article caching beta feature
            const articleCachingLabel = document.getElementById('article-caching-label');
            if (articleCachingLabel) {
                // Keep the beta tag and add the translation
                const betaTag = articleCachingLabel.querySelector('.beta-tag');
                if (betaTag) {
                    articleCachingLabel.textContent = '';
                    articleCachingLabel.appendChild(betaTag);
                    articleCachingLabel.appendChild(document.createTextNode(' ' + this.getLocaleString('article_caching_title')));
                } else {
                    articleCachingLabel.textContent = this.getLocaleString('article_caching_title');
                }
            }
            
            const cachingDesc = articleCachingLabel?.closest('.beta-feature')?.querySelector('.beta-feature-description');
            if (cachingDesc) {
                cachingDesc.textContent = this.getLocaleString('article_caching_description');
            }
            
            // Add tooltip translation for article caching
            const cachingTooltip = articleCachingLabel?.closest('.beta-feature')?.querySelector('.beta-tooltip');
            if (cachingTooltip) {
                cachingTooltip.textContent = this.getLocaleString('article_caching_tooltip');
            }
            
            // Update other UI elements as needed
            console.log('UI updated with locale:', currentLocale);
        } catch (error) {
            console.error('Error updating UI with locale:', error);
        }
    }
};

// Export functions for browser
if (typeof window !== 'undefined') {
    // When loaded as a regular script in the browser
    window.getLocaleString = (key, ...args) => window.AIPediaLocales.getLocaleString(key, ...args);
    window.setLocale = (locale) => window.AIPediaLocales.setLocale(locale);
    window.getLocale = () => window.AIPediaLocales.getLocale();
    window.updateUIWithLocale = () => window.AIPediaLocales.updateUIWithLocale();
    window.loadSavedLocale = () => window.AIPediaLocales.loadSavedLocale();
}

// For CommonJS environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.AIPediaLocales;
} 